### ISSUE TITLE
balena depends on random to be initialised before starting

### ISSUE THREAD

**Issue by ZubairLK** [balena-os/balena-engine#105]
Until crng has been initialised and there is enough entropy in the system, balena does not start.

This is introduced by a patch in the kernel which was backported to stable branches as well. 
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=43838a23a05fbd13e47d750d3dfd77001536dd33 

Reverting this patch does make balena start faster.
tl;dr Kernel used to report crng initialised when it had a small amount of entropy. Now it reports crng initialised correctly when there is good entropy.

Worst case I've seen until now is ~7 minutes
```
root@2410213:~# dmesg | grep -i random
...
[    1.182282] random: systemd: uninitialized urandom read (16 bytes read)
[  444.351446] random: crng init done
[  444.351453] random: 7 urandom warning(s) missed due to ratelimiting
root@2410213:~#
```
As a result, balena starts 7 minutes later.

Various packages have fixed this in various ways.
e.g. In util-linux, a flag was passed to getrandom to make the call nonblocking 
https://github.com/karelzak/util-linux/commit/a9cf659e0508c1f56813a7d74c64f67bbc962538#diff-6341cb5466770a24a1f3bfdb80803412

Lots of Debian chatter about it. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897572

From a cursory look, it looks like packages which wanted random (but not necessarily entropy in the security sense e.g. uuid generation) basically called getrandom with a nonblock flag so whatever random numbers came was fine.

Security stuff like ssh key gen basically have to wait. Or install something like rng-tools to improve entropy at boot faster.

**Description**

**Steps to reproduce the issue:**
1. Boot resinOS v2.19 on a nuc image in a VM
2. Check if balena is starting immediately on boot
3. Check if balena starts after you see the crng init message comes when you type random stuff on the keyboard

**Describe the results you received:**
Balena starts after crng init.

**Describe the results you expected:**
Balena should start at boot

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `balena version`:**

```
root@resin:~# balena version
Client:
 Version:	unknown-version
 API version:	1.35
 Go version:	go1.9.7
 Git commit:	unknown-commit
 Built:	unknown-buildtime
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	17.12.0-dev
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.7
  Git commit:	3e2973d26934bd22c46f07764afb1ed8b11bf6a1
  Built:	Tue Oct  2 12:18:21 2018
  OS/Arch:	linux/amd64
  Experimental:	true
root@resin:~# 

```

**Output of `balena info`:**

```
root@resin:~# balena info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 17.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 41
 Dirperm1 Supported: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan null
 Log: journald json-file
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Runtimes: bare runc
Default Runtime: runc
Init Binary: balena-init
containerd version: 
runc version: 13e66eedaddfbfeda2a73d23701000e4e63b5471
init version: 949e6fa-dirty (expected: 949e6facb7738)
Kernel Version: 4.14.48-yocto-standard
Operating System: Resin OS 2.15.1+rev2
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 989.3MiB
Name: resin
ID: 4FGZ:T47Z:U7X6:45DJ:4J7P:YFN3:QQM4:WOZ3:TTBL:UMQM:QOCU:7M6V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 128
 Goroutines: 101
 System Time: 2018-10-08T17:23:38.887619837Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 192.168.1.166:5000
 127.0.0.0/8
Live Restore Enabled: false

root@resin:~# 
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by floion** [comment]
@petrosagg ping on this

**Comment by robertgzr** [comment]
Fixed by #123

**Comment by chpeps** [comment]
I still see this probleme 

```
root@6c35b9d:~# dmesg | grep -i random
...
[    7.668674] random: systemd: uninitialized urandom read (16 bytes read)
[  195.124100] random: crng init done
[  195.124139] random: 7 urandom warning(s) missed due to ratelimiting
root@6c35b9d:~#
```
**Description**
**Steps to reproduce the issue:**

1. Boot resinOS v2.44.0+rev1 on a Raspberry Pi Zero W
2. Without keyboard or mouse (Only the supply power)

**Describe the results you received:**
Balena starts after crng init.

**Describe the results you expected:**
Balena should start at boot

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `balena version`:**
```
root@6c35b9d:~# balena version
Client:
 Version:           18.09.10-dev
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        7cb464a406748016f2df0c31a9851d20456a3d31
 Built:             Thu Oct 17 14:28:36 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.09.10-dev
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       7cb464a406748016f2df0c31a9851d20456a3d31
  Built:            Thu Oct 17 14:28:36 2019
  OS/Arch:          linux/arm
  Experimental:     true
root@6c35b9d:~#
```

**Output of `balena info`:**
```
root@6c35b9d:~# balena info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 18.09.10-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host ipvlan null
 Log: journald json-file local
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Runtimes: bare runc
Default Runtime: runc
Init Binary: balena-engine-init
containerd version: 
runc version: b3d5036b6520060db00c81352d533a5dd919aaaf
init version: 949e6fa-dirty (expected: fec3683b971d9)
Kernel Version: 4.19.71
Operating System: balenaOS 2.44.0+rev1
OSType: linux
Architecture: armv6l
CPUs: 1
Total Memory: 479.4MiB
Name: 6c35b9d
ID: 6W6G:AE3G:N44J:PACE:NJ7S:U5U2:YMSE:ZZLT:HRSI:2QZO:PGNM:LXRN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No cpuset support
root@6c35b9d:~#
```

**Comment by robertgzr** [comment]
@chpeps how long is the delay you experience? Can you post the output of `sytemd-analyze blame`

**Comment by chpeps** [comment]
about ~6 minutes after power on.

**Output of `systemd-analyze time`:**
```
root@6c35b9d:~# systemd-analyze time
Startup finished in 6.414s (kernel) + 4min 54.135s (userspace) = 5min 550ms 
multi-user.target reached after 4min 53.863s in userspace
```
**Output of `systemd-analyze blame`:**
```
root@6c35b9d:~# systemd-analyze blame
     1min 2.909s resin-supervisor.service
         55.448s balena.service
         18.100s os-networkmanager.service
         12.812s os-udevrules.service
         12.798s os-sshkeys.service
         12.318s balena-device-uuid.service
         11.502s dev-disk-by\x2dpartuuid-ef943c7a\x2d02.device
         11.330s mnt-sysroot-active.service
          9.551s resin-net-config.service
          9.517s dev-disk-by\x2dlabel-resin\x2dstate.device
          9.315s systemd-udev-settle.service
          8.738s resin-persistent-logs.service
          7.638s dev-mmcblk0p1.device
          5.654s dev-mmcblk0p6.device
          4.576s resin-proxy-config.service
          3.687s resin-hostname.service
          3.428s prepare-openvpn.service
          3.198s ModemManager.service
          2.452s resin-filesystem-expand.service
          2.215s systemd-udev-trigger.service
          1.920s systemd-logind.service
          1.701s timeinit-timestamp.service
          1.158s resin-state.service
           805ms bind-etc-hostname.service
           786ms var-volatile-srv.service
           762ms systemd-journald.service
           757ms bind-etc-NetworkManager-system-connections.service
           740ms systemd-update-utmp.service
           729ms var-volatile-spool.service
           726ms bind-var-lib-bluetooth.service
           657ms bind-etc-docker.service
           646ms var-volatile-cache.service
           616ms bind-var-lib-NetworkManager.service
           605ms sys-kernel-config.mount
           584ms bind-home-root-.ssh.service
           554ms resin-init.service
           534ms NetworkManager.service
           489ms os-config-devicekey.service
           458ms tmp.mount
           389ms systemd-tmpfiles-clean.service
           373ms systemd-tmpfiles-setup-dev.service
           315ms resin-data.service
           301ms plymouth-start.service
           290ms wpa_supplicant.service
           281ms systemd-udevd.service
           220ms dnsmasq.service
           192ms systemd-update-utmp-runlevel.service
           177ms balena-host.socket
           143ms sshd.socket
           134ms systemd-tmpfiles-setup.service
           132ms var-volatile.mount
           129ms var-lib-docker.mount
           129ms sshd@1-10.240.7.180:22222-52.4.252.97:43724.service
           126ms avahi-daemon.service
           115ms resin\x2ddata.mount
            96ms systemd-random-seed.service
            93ms plymouth-read-write.service
            85ms systemd-rfkill.service
            43ms balena-engine.socket
```
